/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package inv.view;

import inv.controller.InvoiceController;
import inv.model.InvoiceHeader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author DELL
 */
public class AppFrame extends javax.swing.JFrame {

    /**
     * Creates new form AppFrame
     */
        private InvoiceController controller ;  

    TableModel invoiceModel;
    public AppFrame() {
        controller = new InvoiceController(this);
        initComponents();
        String invoice[]= {"Number Invoice","Date Invoice","Customer Name","Total Invoice"};
         invoiceModel=new DefaultTableModel(invoice,3);
        salesInvoiceTable.setModel(invoiceModel);
        String items[]= {"Item Number","Item Name","Item Price","Count","Total"};
        TableModel itemModel=new DefaultTableModel(items,4);
        salesInvoiceItemTable.setModel(itemModel);
        
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        salesInvoiceTable = new javax.swing.JTable();
        creatInvBtn = new javax.swing.JButton();
        delInvBtn = new javax.swing.JButton();
        delInvBtn.addActionListener(controller);
        salesInvoiceNumber = new javax.swing.JLabel();
        salesInvoiceDate = new javax.swing.JLabel();
        salesInvoiceCusName = new javax.swing.JLabel();
        salesInvoiceTotal = new javax.swing.JLabel();
        custLbl = new javax.swing.JLabel();
        numLbl = new javax.swing.JLabel();
        dateLbl = new javax.swing.JLabel();
        totalLbl = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        salesInvoiceItemTable = new javax.swing.JTable();
        createNewItemBtn = new javax.swing.JButton();

        delItemBtn = new javax.swing.JButton();
        delItemBtn.addActionListener(controller);
        jMenuBar1 = new javax.swing.JMenuBar();
        salesInvoiceMenu = new javax.swing.JMenu();
        loadMenuSalesInvoiceItem = new javax.swing.JMenuItem();
        loadMenuSalesInvoiceItem.addActionListener(controller);
        saveMenuSalesInvoiceItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        salesInvoiceTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(salesInvoiceTable);

        creatInvBtn.setText("Create Invoice");
        creatInvBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                creatInvBtnActionPerformed(evt);
            }
        });

        delInvBtn.setText("Delete Invoice");

        salesInvoiceNumber.setText("Invoice Num");

        salesInvoiceDate.setText("Invoice Date");

        salesInvoiceCusName.setText("Customer Name");

        salesInvoiceTotal.setText("Invoice Total");

        custLbl.setText(".");

        numLbl.setText(".");

        dateLbl.setText(".");

        totalLbl.setText(".");

        salesInvoiceItemTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(salesInvoiceItemTable);

        createNewItemBtn.setText("New Item");

        delItemBtn.setText("Delete Item");

        salesInvoiceMenu.setText("File");

        loadMenuSalesInvoiceItem.setText("Load Files");
        loadMenuSalesInvoiceItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadMenuSalesInvoiceItemActionPerformed(evt);
            }
        });
        salesInvoiceMenu.add(loadMenuSalesInvoiceItem);

        saveMenuSalesInvoiceItem.setText("Save Data");
        saveMenuSalesInvoiceItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveMenuSalesInvoiceItemActionPerformed(evt);
            }
        });
        salesInvoiceMenu.add(saveMenuSalesInvoiceItem);

        jMenuBar1.add(salesInvoiceMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(creatInvBtn)
                        .addGap(66, 66, 66)
                        .addComponent(delInvBtn)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(salesInvoiceCusName)
                                    .addComponent(salesInvoiceNumber)
                                    .addComponent(salesInvoiceDate)
                                    .addComponent(salesInvoiceTotal))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(totalLbl)
                                    .addComponent(dateLbl)
                                    .addComponent(numLbl)
                                    .addComponent(custLbl)))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addComponent(createNewItemBtn)
                        .addGap(61, 61, 61)
                        .addComponent(delItemBtn)))
                .addContainerGap(155, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(salesInvoiceNumber)
                            .addComponent(numLbl))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(salesInvoiceDate)
                            .addComponent(dateLbl))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(salesInvoiceCusName)
                            .addComponent(custLbl))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(salesInvoiceTotal)
                            .addComponent(totalLbl))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(creatInvBtn)
                    .addComponent(delInvBtn)
                    .addComponent(createNewItemBtn)
                    .addComponent(delItemBtn))
                .addContainerGap(182, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loadMenuSalesInvoiceItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadMenuSalesInvoiceItemActionPerformed
        // TODO add your handling code here:

        
    }//GEN-LAST:event_loadMenuSalesInvoiceItemActionPerformed

    private void saveMenuSalesInvoiceItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveMenuSalesInvoiceItemActionPerformed
        // TODO add your handling code here:
        String path="invoice.csv";
        File file= new File(path);
        try{
            FileWriter fw=new FileWriter(path);
            BufferedWriter br=new BufferedWriter(fw);
            for(int i=0;i<salesInvoiceTable.getRowCount();i++){
                for(int j=0;j<salesInvoiceTable.getColumnCount();j++){
                    br.write(salesInvoiceTable.getValueAt(i, j).toString());
                    br.write(",");
                }
                br.newLine();
            }
            br.close();
        }catch(IOException e){
            System.out.println(e);
            
        }
    }//GEN-LAST:event_saveMenuSalesInvoiceItemActionPerformed

    private void creatInvBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_creatInvBtnActionPerformed
        // TODO add your handling code here:
        InvoiceHeader invHeader=new InvoiceHeader();
        invHeader.setNo((int) salesInvoiceTable.getValueAt(1, 1));
        numLbl.setText(String.valueOf(invHeader.getNo()));
        Date date=(Date) salesInvoiceTable.getValueAt(1, 2);
        dateLbl.setText(String.valueOf(date));
        String name=(String) salesInvoiceTable.getValueAt(1, 3);
        custLbl.setText(name);

    }//GEN-LAST:event_creatInvBtnActionPerformed

    /**
     * @param args the command line arguments
     */

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AppFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AppFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AppFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AppFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AppFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton creatInvBtn;
    private javax.swing.JButton createNewItemBtn;
    private javax.swing.JLabel custLbl;
    private javax.swing.JLabel dateLbl;
    private javax.swing.JButton delInvBtn;
    private javax.swing.JButton delItemBtn;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JMenuItem loadMenuSalesInvoiceItem;
    private javax.swing.JLabel numLbl;
    private javax.swing.JLabel salesInvoiceCusName;
    private javax.swing.JLabel salesInvoiceDate;
    private javax.swing.JTable salesInvoiceItemTable;
    private javax.swing.JMenu salesInvoiceMenu;
    private javax.swing.JLabel salesInvoiceNumber;
    private javax.swing.JTable salesInvoiceTable;
    private javax.swing.JLabel salesInvoiceTotal;
    private javax.swing.JMenuItem saveMenuSalesInvoiceItem;
    private javax.swing.JLabel totalLbl;
    // End of variables declaration//GEN-END:variables
}
